version: "3.1"
services:
  api:
    image: miacastroco/reservations
    restart: always
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
    networks:
      - postgres
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: whygodwhy
      POSTGRES_USER: developer
      POSTGRES_DB: reservationdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db-data:
    driver: local
